Repository AlexanderKrysiuk/LinkUp-Frontend, pull requests merged in 2023-10, with the labels that each got.

#31 Feature/calendar
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.css
  src/components/BackdropComponent.tsx
  src/components/ModalComponent.css
  src/components/ModalComponent.css.map
  src/components/ModalComponent.scss
  src/components/ModalComponent.tsx
  src/components/calendar/CalendarComponent.css
  src/components/calendar/CalendarComponent.css.map
  src/components/calendar/CalendarComponent.scss
  src/components/calendar/CalendarComponent.tsx
  src/components/calendar/CalendarField/CalendarFieldComponent.tsx
  src/components/calendar/CalendarField/CalendarMeetingsComponent.tsx
  src/components/calendar/CalendarHeader/CalendarArrowComponent.tsx
  src/components/calendar/CalendarHeader/CalendarDayNamesComponent.tsx
  src/components/calendar/CalendarHeader/CalendarHeaderComponent.tsx
  src/components/hamburger/HamburgerLinkComponent.tsx
  src/components/navbar/hamburger/HamburgerIconComponent.tsx
  src/contexts/BackdropContext.tsx
  src/contexts/ModalContext.tsx
  src/hooks/BackdropHooks.tsx
  src/hooks/ModalHooks.tsx
  src/layouts/FormLayout.css
  src/layouts/FormLayout.css.map
  src/layouts/FormLayout.scss
  src/main.tsx
  src/middleware/meetingsHandler.ts
  src/pages/HomePage.tsx
  src/pages/MockPage.tsx
  src/utils/CalendarHelpers/calendarConstants.ts
  src/utils/CalendarHelpers/calendarFunctions.ts
  src/utils/CalendarHelpers/calendarHandlers.ts
  src/utils/calendarUtils.ts
  src/utils/placeholder
  tsconfig.json
  vite.config.ts
Labels: enhancement

#35 Documentation/#2
  src/App.tsx
  src/components/formUtils/DividerComponent.tsx
  src/components/meeting/ArchivedMeetingsComponent.tsx
  src/components/meeting/MeetingComponent.tsx
  src/components/meeting/MeetingsListComponent.tsx
  src/components/meeting/UpcomingMeetingsComponent.tsx
  src/components/meetingForm/NewMeetingForm.tsx
  src/components/profile/header/userdetails/AboutComponent.tsx
  src/components/profile/header/userdetails/PhotoComponent.tsx
  src/components/profile/header/userdetails/PhotoUploaderComponent.tsx
  src/data/dataTypes.ts
  src/middleware/apiHandler.ts
  src/middleware/authHandler.ts
  src/middleware/formHandler.ts
  src/middleware/helpers/dataConverter.ts
  src/middleware/meetingsHandler.ts
  src/middleware/userHandler.ts
Labels: documentation

#36 Feature/new meeting form modal
  src/components/bookMeeting/ContractorCard.tsx
  src/components/bookMeeting/ContractorMeetingsList.tsx
  src/components/hamburger/HamburgerLinkComponent.tsx
  src/components/meetingForm/NewMeetingForm.tsx
  src/components/navbar/hamburger/HamburgerIconComponent.tsx
  src/components/navbar/iconbutton/NavbarIconButtonComponent.tsx
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/MockPage.tsx
Labels: enhancement, bugfix
